title: The Right to Tinker Initiative
description: Advocating for the freedom to modify, repair, and improve your own devices.
url: "https://right2tinker.org" 
baseurl: "" # Change this to "/your-repo-name" if not using a custom domain or user page
